### ISSUE TITLE
Update compatibility to Capacitor 4

### ISSUE THREAD

**Issue by josuelmm** [capawesome-team/capacitor-badge#33]
Update compatibility to Capacitor 4

**Comment by robingenz** [comment]
I will release the update next week. I am currently on vacation.

**Comment by robingenz** [comment]
You can give it a try:

```
npm i @robingenz/capacitor-badge@1.2.1-dev.6111d44.1659196262
```

**Comment by robingenz** [comment]
> You can give it a try:
> 
> ```
> npm i @robingenz/capacitor-badge@1.2.1-dev.6111d44.1659196262
> ```

Sorry, this build is broken. New one:

```
npm i @robingenz/capacitor-badge@1.2.1-dev.0c1c23b.1659199300
```

**Comment by josuelmm** [comment]
Thanks you

**Comment by josuelmm** [comment]
Runs excellent and compiles everything without problem

**Comment by robingenz** [comment]
@josuelmm Thank you for testing!

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/182923963-c93db7fa-5fae-48de-acad-a2dc511dcc81.png)
iam clean cache but dont change`@capawesome/capacitor-badge` name

**Comment by robingenz** [comment]
Did you run the following?

```
npm rm @robingenz/capacitor-badge
npm install @capawesome/capacitor-badge
npx cap sync
```

**Comment by productdevbook** [comment]
> @productdevbook Did you run the following?
> 
> ```
> npm rm @robingenz/capacitor-badge
> npm install @capawesome/capacitor-badge
> npx cap sync
> ```

yes some, but dont remove 

![image](https://user-images.githubusercontent.com/38668796/182926804-c6c1e67e-1a2a-4d5c-ae38-944788d362b7.png)

**Comment by robingenz** [comment]
> > @productdevbook Did you run the following?
> > ```
> > npm rm @robingenz/capacitor-badge
> > npm install @capawesome/capacitor-badge
> > npx cap sync
> > ```
> 
> yes some, but dont remove
> 
> ![image](https://user-images.githubusercontent.com/38668796/182926804-c6c1e67e-1a2a-4d5c-ae38-944788d362b7.png)

@productdevbook So it works now?

**Comment by productdevbook** [comment]
no work, dont add android studio, reload studio but some problem
![image](https://user-images.githubusercontent.com/38668796/182927266-62dd9eb5-6ecc-4761-af01-eb56729b16f2.png)

![image](https://user-images.githubusercontent.com/38668796/182927427-c806da02-c19e-4ce8-8fad-b5274ad5d09f.png)

**Comment by robingenz** [comment]
Try `File` -> `Invalidate Caches and Restart` and then `Sync Project with Gradle files` in Android Studio. Does this work? @productdevbook

**Comment by productdevbook** [comment]
thank you fixed, but app dont lanch dont error

**Comment by robingenz** [comment]
@productdevbook Please create a new issue with all the information you have and an example to reproduce so we don't spam this issue.
