### ISSUE TITLE
bug: badge.isSupported is false in the android device

### ISSUE THREAD

**Issue by balya7777** [capawesome-team/capacitor-badge#36]
**Plugin version:**

2.0.0

**Platform(s):**

android

**Current behavior:**
The result of badge.requestPermissions is granted, but badge.isSupported is false.

**Expected behavior:**
I think once permission is granted, badge has to be supported.

**Comment by robingenz** [comment]
This plugin does not support all Android devices (see [Quirks](https://github.com/capawesome-team/capacitor-badge#quirks)).
