### ISSUE TITLE
bug: First notification gets deleted because of setting badge to 0

### ISSUE THREAD

**Issue by diego2k** [capawesome-team/capacitor-badge#38]
**Plugin version:**
2.0.0

**Platform(s):**
iOS

**Current behavior:**
First notification gets deleted because restore() is setting badge to 0. 

**Expected behavior:**
First notification behaves the same as second, third etc. 

**Steps to reproduce:**
App supports notifications and badge.
No notifications for app are present. 
App is closed. 
Send notification to app. 
The first notification will arrive on the device, and in a second it will disappear from lock screen. 
Badge will be one. 

If the app is open in the background it will work, also it works for the 2., 3., 4. etc. notification. 

**Related code:**
To fix this, open Badge.swift and do something like that: 

```
    @objc private func restore() {
        let count = get()
        if(count > 0){
          set(count: count, completion: {})
        }
    }
```

**Other information:**
What I think happens. If there is no notification, and the first one arrives the restore() is called, and get() delivers 0, the set(0) will delete all notifications for the app. Afterwards the set() is called which increases the badge to one. 
For the second notification it works obviously because get() will return >0 which will not delete the notifications.

**Comment by robingenz** [comment]
Thank you for your request!
Can you please give this dev build a try:

```
npm i @capawesome/capacitor-badge@2.0.0-dev.ea15a38.1664364775
```

**Comment by diego2k** [comment]
Thanks, this version works.
