### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by lightroyal** [capawesome-team/capacitor-badge#45]
**Plugin version:**

version ^1.2.1

**Platform(s):**

Samsung S10 
Android 12

**Current behavior:**

Badge.clear() not working, the number of notifications is still shown

**Expected behavior:**

Badge.clear() should clear the number of notifications in the app badge

**Steps to reproduce:**

Well I don't really know, just call Badge.clear().then()

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/android: 3.4.3
  @capacitor/core: 3.4.0
  @capacitor/ios: 3.4.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

**Comment by robingenz** [comment]
Hi @lightroyal,
thank you for your request.

> Well I don't really know, just call Badge.clear().then()

I do this in my demo app and it works.

Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so I can debug the issue.

**Comment by lightroyal** [comment]
So, after further testing I found out that if I clear the notifications from the notifications center of the S12 their badge counter gets reset, I don't know if this helps? 

As for the reproducible example, I use your exact the code of your demo app, don't get me wrong it works in a P30 (android) and also in every iPhone, maybe this is a common behavior in Samsung phones, unfortunately I only have a P30 to test this on.

**Comment by robingenz** [comment]
> maybe this is a common behavior in Samsung phones

Yes, that's possible. Unfortunately, there is nothing I can do. You would have to report it here: https://github.com/leolin310148/ShortcutBadger

For this reason i am closing this issue.
