### ISSUE TITLE
bug: Cannot fing 'getConfig' in scope (iOS)

### ISSUE THREAD

**Issue by drcll** [capawesome-team/capacitor-badge#49]
**Plugin version:**

   "@capawesome/capacitor-badge": "^2.0.2",

**Platform(s):**

ios

**Current behavior:**

While building iOS version I got this error "Cannot fing 'getConfig' in scope" 
in this method

private func badgeConfig() -> BadgeConfig {
    var config = BadgeConfig()
    config.persist = getConfig().getBoolean("persist", config.persist)
    config.autoClear = getConfig().getBoolean("autoClear", config.autoClear)
    return config
  }

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
Thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.

**Comment by drcll** [comment]
Thank you for reply.

This is package json for project where it's not working.

`{
  "name": "badge-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@awesome-cordova-plugins/core": "^5.39.0",
    "@awesome-cordova-plugins/file-opener": "^5.41.0",
    "@capacitor-community/apple-sign-in": "^1.0.1",
    "@capacitor-community/barcode-scanner": "^2.0.1",
    "@capacitor-community/facebook-login": "^3.3.0",
    "@capacitor/android": "^3.4.3",
    "@capacitor/app": "^1.1.0",
    "@capacitor/browser": "^1.0.7",
    "@capacitor/cli": "^3.3.2",
    "@capacitor/core": "^3.3.2",
    "@capacitor/device": "^1.1.1",
    "@capacitor/dialog": "^1.0.7",
    "@capacitor/filesystem": "^1.1.0",
    "@capacitor/geolocation": "^1.3.1",
    "@capacitor/ios": "^3.3.2",
    "@capacitor/local-notifications": "^1.1.0",
    "@capacitor/push-notifications": "^1.0.7",
    "@capacitor/splash-screen": "^1.2.1",
    "@capacitor/storage": "^1.2.3",
    "@capawesome/capacitor-badge": "^2.0.2",
    "@capgo/native-market": "^1.1.10",
    "@codetrix-studio/capacitor-google-auth": "3.1.0",
    "@ericblade/quagga2": "^1.6.0",
    "apexcharts": "^3.37.1",
    "axios": "^0.21.1",
    "capacitor-native-biometric": "^3.0.3",
    "capacitor-native-settings": "^0.1.0",
    "capacitor-plugin-safe-area": "^0.0.3",
    "cordova-plugin-file-opener2": "^3.0.5",
    "core-js": "^3.6.5",
    "dotenv": "^16.0.1",
    "dropzone": "^5.9.2",
    "flatpickr": "^4.6.9",
    "fslightbox": "^3.3.0-2",
    "jetifier": "^2.0.0",
    "jsbarcode": "^3.11.5",
    "laravel-echo": "^1.11.1",
    "lodash": "^4.17.21",
    "mobius1-selectr": "^2.4.13",
    "pusher-js": "^7.0.3",
    "qrcode": "^1.5.0",
    "register-service-worker": "^1.7.1",
    "rxjs": "^7.5.4",
    "typescript": "^4.7.4",
    "vue": "^2.6.11",
    "vue-apexcharts": "^1.6.2",
    "vue-axios": "^3.2.4",
    "vue-echo-laravel": "^0.1.0",
    "vue-lodash": "^2.1.2",
    "vue-moment": "^4.1.0",
    "vue-qrcode-component": "^2.1.1",
    "vue-router": "^3.2.0",
    "vue-sweetalert2": "^5.0.2",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.5.0",
    "@vue/cli-plugin-pwa": "^4.5.0",
    "@vue/cli-service": "^4.5.0",
    "sass": "^1.49.11",
    "sass-loader": "^8.0.2",
    "vue-template-compiler": "^2.6.11"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}`

It's Vue 2 app. For reproducing just use commands 
yarn build
cap sync ios

and build app in Xcode

**Comment by robingenz** [comment]
Please provide a Minimal, Reproducible Example as described in [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) in a public GitHub repository.

**Comment by drcll** [comment]
https://github.com/drcll/capacitor-badge

**Comment by robingenz** [comment]
You use Capacitor 3. The latest version of this plugin supports only Capacitor 4.
Please update to Capacitor 4 or install the deprecated version of this plugin: https://www.npmjs.com/package/@robingenz/capacitor-badge
